/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Muestreo.Temperatura;
import Muestreo.Traslacion;
import Muestreo.Umbralizacion;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author CESAR IVAN MTZ
 */
public class JFrameFrio extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDeslizable
     */
     private Image image2, imageAux;
     private int prueba;
    
    public JFrameFrio(Image image1) {
        initComponents();
        //this.jLabelImagen.setIcon(new ImageIcon(imagenOriginal));
        this.image2=image1;
        this.labelImage1.setIcon(new ImageIcon(this.image2));
        this.LabelImage2.setIcon(new ImageIcon(Temperatura.generarImagenFria(Traslacion.generarImagenBrillo(image2, 69), 100)));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImage1 = new javax.swing.JLabel();
        LabelImage2 = new javax.swing.JLabel();
        temperaturaS = new javax.swing.JSlider();
        Brillo = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        temperaturaS.setMaximum(510);
        temperaturaS.setPaintTicks(true);
        temperaturaS.setValue(255);
        temperaturaS.setValueIsAdjusting(true);
        temperaturaS.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                temperaturaSStateChanged(evt);
            }
        });

        Brillo.setMaximum(255);
        Brillo.setPaintTicks(true);
        Brillo.setValue(127);
        Brillo.setValueIsAdjusting(true);
        Brillo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BrilloStateChanged(evt);
            }
        });

        jLabel1.setText("Temperatura");

        jLabel2.setText("Brillo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelImage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelImage2)
                .addGap(0, 394, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperaturaS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Brillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImage1)
                    .addComponent(LabelImage2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Brillo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temperaturaS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperaturaSStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_temperaturaSStateChanged
        // TODO add your handling code here:
        if(this.temperaturaS.getValue()>255){
             imageAux=Temperatura.generarImagenCaliente(image2, 255-this.temperaturaS.getValue());
             this.LabelImage2.setIcon(new ImageIcon(Temperatura.generarImagenCaliente(image2, this.temperaturaS.getValue()-255)));
        }else{
             imageAux=Temperatura.generarImagenFria(image2, this.temperaturaS.getValue());
             this.LabelImage2.setIcon(new ImageIcon(Temperatura.generarImagenFria(image2, 255-this.temperaturaS.getValue())));
        }
       
       // System.out.println(this.temperaturaS.getValue());
        //prueba = this.temperaturaS.getValue();
    }//GEN-LAST:event_temperaturaSStateChanged

    private void BrilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BrilloStateChanged
        // TODO add your handling code here:
        
        //image2=Traslacion.generarImagenBrillo(image2, this.Brillo.getValue())
         this.LabelImage2.setIcon(new ImageIcon(Traslacion.generarImagenBrillo(imageAux, this.Brillo.getValue())));
       // System.out.println(this.temperaturaS.getValue());
    }//GEN-LAST:event_BrilloStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrameDeslizable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrameDeslizable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrameDeslizable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrameDeslizable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameDeslizable().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Brillo;
    private javax.swing.JLabel LabelImage2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelImage1;
    private javax.swing.JSlider temperaturaS;
    // End of variables declaration//GEN-END:variables
}
